### PR TITLE
added gmail api

### PR DESCRIPTION
**Pull request by wogus00**
you would need the credentials.json file to get gmail api working. So far, I only made the 5 gmail accounts available for testing. So if you try to log in with other account, it will not work. 
If you don't have access, please let me know.

### CODE REVIEW

**Comment by wogus00** [comment]
additional note: i had to delete classes related to login feature to check if this actually works or not.

**Review by ShioTatsu-Japan — COMMENTED** [review]
Do you think we need to consider API limitations and quotas?

**Comment by wogus00** [comment]
I don't think so, I think it allows up to 10000 requests?

**Review by ShioTatsu-Japan — APPROVED** [review]
ok so we don't need to consider unusual case:) then I think this should be fine!

**Pull request merged**
