### PR TITLE
Completed Complete Task Use Case

### PR DESCRIPTION
**Pull request by wogus00**
Please review my completed version of complete task use case

### CODE REVIEW

**Review by Kosei1227 — APPROVED** [review]
good custom of trying and catching errors.

The implementation of CompleteTask is totally straightforward to me.
If you test the sample completing tasks and the codes do not fail, I think you should merge it to the main branch.

**Comment by Kosei1227** [comment]
I did not notice the intentional mistake you made as indicated on Discord.
Unless the code is not running, we should not merge pull request. Sorry about that.

**Review by ShioTatsu-Japan — CHANGES_REQUESTED** [review]
I've run the main.java as instructed and encountered an issue with the CompleteTaskView. It appears the textfield is missing. Once this is addressed, I think the feature will be closer to completion. I also attached screenshot here.
Screenshot 2023-11-19 at 11 30 46

**Comment by ShioTatsu-Japan** [comment]
I also noticed there is a security issue. Currently, any user can complete a task if they know the task’s name. To enhance the security and functionality, I would suggest we add an inputData parameter that verifies userEmail. This would ensure that a task can only be completed by assigned individual.

**Comment by wogus00** [comment]
> I've run the main.java as instructed and encountered an issue with the CompleteTaskView. It appears the textfield is missing, which is in line with the note on the deliberate omission for testing purposes. Once this is addressed, I believe the feature will be closer to completion. I also attached screenshot here. Screenshot 2023-11-19 at 11 30 46

Thank you for the testing. I just added the input text field and tested it (attaching screenshot as well)

**Comment by wogus00** [comment]
> I also noticed there is a security issue. Currently, any user can complete a task if they know the task’s name. To enhance the security and functionality, I would suggest we add an inputData parameter that verifies userEmail. This would ensure that a task can only be completed by assigned individual.

I will work on this today and request for review again

**Comment by wogus00** [comment]
update: added userEmail parameter for inputData for the issue mentioned by @ShioTatsu-Japan.
Also added all createTask use case here as well. So please check those as well.
Similar to Complete Task use case, I couldn't complete the DAO part because we haven't agreed on the firebase design.

**Comment by wogus00** [comment]
update: added javadocs for my responsible use cases.

**Review by Kosei1227 — COMMENTED** [review]
I've looked through the java docs.
You already have detailed explanations about parameters.
I will also include parameters explanation to my java docs

**Comment by wogus00** [comment]
update: added classes for usecase "modify task"

**Review by ShioTatsu-Japan — APPROVED** [review]

**Review by ShioTatsu-Japan — APPROVED** [review]
Thank you for reviewing my request! I think your code are ready to merge. This might be a GitHub custom, but the some parts of your codes had missing indent problem.

**Pull request merged**
